/*
 * low_level_init_stm32f4xx.c
 *
 *  Created on: 20 March 2013
 *      Author: Maxime Vincent
 * Description: Low-level initialization functions for the STM32-F4 Discovery
 *              Heavily based on the STMicro code found in their Firmware
 *              Library. This will set-up system clocks and will relocate the
 *              the Vector Table to internal SRAM.
 *              
 *
 *     Purpose: Purpose is to demonstrate what a low-level init routine could 
 *              look like. 
 *
 *     Context: Written in the context of the Embedded C course by TASS Belgium.
 * 
 *    Comments: This file contains the system clock configuration for STM32F4xx
 *              devices, and is generated by the clock configuration tool
 *              stm32f4xx_Clock_Configuration_V1.0.0.xls
 *
 *              Parts of this file are (C) COPYRIGHT 2011 STMicroelectronics 
 *             
 * 1.  This file provides a functions and one global variable to be called from 
 *     user application:
 *      - SystemInit(): Setups the system clock (System clock source,
 *                      PLL Multiplier and Divider factors, AHB/APBx prescalers
 *                      and Flash settings), depending on the configuration
 *                      made in the clock xls tool. 
 *                      This function is called at startup just after reset and 
 *                      before branch to main program. This call is made inside
 *                      the "startup_stm32f4xx.s" file.
 *
 *      - SystemCoreClock variable: Contains the core clock (HCLK), it can be
 *                                  used by the user application to setup the
 *                                  SysTick timer or configure other parameters.
 *                                     
 * 2. After each device reset the HSI (16 MHz) is used as system clock source.
 *    Then SystemInit() function is called, in "startup_stm32f4xx.s" file, to
 *    configure the system clock before to branch to main program.
 *
 * 3. If the system clock source selected by user fails to startup, 
 *    the SystemInit() function will do nothing and HSI still used as system
 *    clock source. User can add some code to deal with this issue inside the
 *    SetSysClock() function.
 *
 * 4. The default value of HSE crystal is set to 8 MHz, refer to "HSE_VALUE" 
 *    define in "stm32f4xx.h" file. When HSE is used as system clock source,
 *    directly or through PLL, and you are using different crystal you have
 *    to adapt the HSE value to your own configuration.
 *
 * 5. This file configures the system clock as follows:
 *=============================================================================
 *        Supported STM32F4xx device revision    | Rev A
 *        System Clock source                    | PLL (HSE)
 *        SYSCLK(Hz)                             | 168000000
 *        HCLK(Hz)                               | 168000000
 *        AHB Prescaler                          | 1
 *        APB1 Prescaler                         | 4
 *        APB2 Prescaler                         | 2
 *        HSE Frequency(Hz)                      | 8000000
 *        PLL_M                                  | 8
 *        PLL_N                                  | 336
 *        PLL_P                                  | 2
 *        PLL_Q                                  | 7
 *        PLLI2S_N                               | NA
 *        PLLI2S_R                               | NA
 *        I2S input clock                        | NA
 *        VDD(V)                                 | 3.3
 *        High Performance mode                  | Enabled
 *        Flash Latency(WS)                      | 5
 *        Prefetch Buffer                        | OFF
 *        Instruction cache                      | ON
 *        Data cache                             | ON
 *        Require 48MHz for USB OTG FS,          | Enabled
 *        SDIO and RNG clock                     |
 *=============================================================================
 */

#include "stm32f4xx.h"

/*!< Uncomment the following line to relocate your vector Table in int SRAM. */
//#define VECT_TAB_SRAM 
/*!< Vector Table base offset field. This value must be a multiple of 0x200. */
#define VECT_TAB_OFFSET  0x00 

/* PLL_VCO = (HSE_VALUE or HSI_VALUE / PLL_M) * PLL_N */
#define PLL_M      8
#define PLL_N      336

/* SYSCLK = PLL_VCO / PLL_P */
#define PLL_P      2

/* USB OTG FS, SDIO and RNG Clock =  PLL_VCO / PLLQ */
#define PLL_Q      7

/* PLLI2S_VCO = (HSE_VALUE Or HSI_VALUE / PLL_M) * PLLI2S_N
   I2SCLK = PLLI2S_VCO / PLLI2S_R */
//#define PLLI2S_N   192
//#define PLLI2S_R   5

  uint32_t SystemCoreClock = 168000000;

__I uint8_t AHBPrescTable[16] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9};

static void set_sys_clock(void);
static void copy_fastcode(void);

extern uint32_t __fastcode_load;
extern uint32_t __fastcode_start;
extern uint32_t __fastcode_end;

/**
  * @brief  Setup the microcontroller system
  *         Initialize the Embedded Flash Interface, the PLL and update the 
  *         SystemFrequency variable.
  * @param  None
  * @retval None
  */
void low_level_init(void)
{
  /* Reset the RCC clock configuration to the default reset state ------------*/
  /* Set HSION bit */
  RCC->CR |= (uint32_t)0x00000001;

  /* Reset CFGR register */
  RCC->CFGR = 0x00000000;

  /* Reset HSEON, CSSON and PLLON bits */
  RCC->CR &= (uint32_t)0xFEF6FFFF;

  /* Reset PLLCFGR register */
  RCC->PLLCFGR = 0x24003010;

  /* Reset HSEBYP bit */
  RCC->CR &= (uint32_t)0xFFFBFFFF;

  /* Disable all interrupts */
  RCC->CIR = 0x00000000;

  /* Configure the System clock source, PLL Multiplier and Divider factors, 
     AHB/APBx prescalers and Flash settings ----------------------------------*/
  set_sys_clock();

  /* Configure the Vector Table location add offset address ------------------*/
#ifdef VECT_TAB_SRAM
  /* Vector Table Relocation in Internal SRAM */
  SCB->VTOR = SRAM_BASE | VECT_TAB_OFFSET;
#else
  /* Vector Table Relocation in Internal FLASH */
  SCB->VTOR = FLASH_BASE | VECT_TAB_OFFSET;
#endif

  /* copy fastcode section from ROM to RAM */
  copy_fastcode();
}

/**
  * @brief  Configures the System clock source, PLL Multiplier and Divider
  *         factors, AHB/APBx prescalers and Flash settings
  * @Note   This function should be called only once the RCC clock configuration
  *         is reset to the default reset state (done in SystemInit() function).
  * @param  None
  * @retval None
  */
static void set_sys_clock(void)
{
/******************************************************************************/
/*            PLL (clocked by HSE) used as System clock source                */
/******************************************************************************/
  __IO uint32_t StartUpCounter = 0, HSEStatus = 0;
  
  /* Enable HSE */
  RCC->CR |= ((uint32_t)RCC_CR_HSEON);
 
  /* Wait till HSE is ready and if Time out is reached exit */
  do
  {
    HSEStatus = RCC->CR & RCC_CR_HSERDY;
    StartUpCounter++;
  } while((HSEStatus == 0) && (StartUpCounter != HSE_STARTUP_TIMEOUT));

  if ((RCC->CR & RCC_CR_HSERDY) != RESET)
  {
    HSEStatus = (uint32_t)0x01;
  }
  else
  {
    HSEStatus = (uint32_t)0x00;
  }

  if (HSEStatus == (uint32_t)0x01)
  {
    /* Enable high performance mode, System frequency up to 168 MHz */
    RCC->APB1ENR |= RCC_APB1ENR_PWREN;
    PWR->CR |= PWR_CR_PMODE;  

    /* HCLK = SYSCLK / 1*/
    RCC->CFGR |= RCC_CFGR_HPRE_DIV1;
      
    /* PCLK2 = HCLK / 2*/
    RCC->CFGR |= RCC_CFGR_PPRE2_DIV2;
    
    /* PCLK1 = HCLK / 4*/
    RCC->CFGR |= RCC_CFGR_PPRE1_DIV4;

    /* Configure the main PLL */
    RCC->PLLCFGR = PLL_M | (PLL_N << 6) | (((PLL_P >> 1) -1) << 16) |
                   (RCC_PLLCFGR_PLLSRC_HSE) | (PLL_Q << 24);

    /* Enable the main PLL */
    RCC->CR |= RCC_CR_PLLON;

    /* Wait till the main PLL is ready */
    while((RCC->CR & RCC_CR_PLLRDY) == 0) { }
   
    /* Configure Flash prefetch, Instruction cache, Data cache and wait state */
    FLASH->ACR = FLASH_ACR_ICEN |FLASH_ACR_DCEN |FLASH_ACR_LATENCY_5WS;

    /* Select the main PLL as system clock source */
    RCC->CFGR &= (uint32_t)((uint32_t)~(RCC_CFGR_SW));
    RCC->CFGR |= RCC_CFGR_SW_PLL;

    /* Wait till the main PLL is used as system clock source */
    while ((RCC->CFGR & (uint32_t)RCC_CFGR_SWS ) != RCC_CFGR_SWS_PLL);
    {
    }
  }
  else
  { /* If HSE fails to start-up, the application will have wrong clock
         configuration. User can add here some code to deal with this error */
  }
}

static void copy_fastcode(void)
{
    uint32_t* load = &__fastcode_load;
    uint32_t* data = &__fastcode_start;

    while(data < &__fastcode_end){
        *(data++) = *(load++);
    }
}
